language: python
python:
  - "2.7"
install:
  - "pip install -r test-requirements.txt -r requirements.txt"
script: nosetests --with-coverage --cover-tests --cover-package=assert_tool
notifications:
  email:
    recipients:
      - mide.ojikutu@gmail.com
